# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\calculator.ui'
#
# Created: Mon Jan 30 20:53:31 2017
#      by: pyside-uic 0.2.15 running on PySide 1.2.2
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(374, 655)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtGui.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(10, 0, 371, 671))
        self.frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.frame_2 = QtGui.QFrame(self.frame)
        self.frame_2.setGeometry(QtCore.QRect(0, 10, 361, 681))
        self.frame_2.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.stackedWidget = QtGui.QStackedWidget(self.frame_2)
        self.stackedWidget.setGeometry(QtCore.QRect(8, 190, 351, 481))
        self.stackedWidget.setStyleSheet("")
        self.stackedWidget.setObjectName("stackedWidget")
        self.std_page = QtGui.QWidget()
        self.std_page.setObjectName("std_page")
        self.PB_Subtraction = QtGui.QPushButton(self.std_page)
        self.PB_Subtraction.setEnabled(True)
        self.PB_Subtraction.setGeometry(QtCore.QRect(268, 211, 81, 50))
        self.PB_Subtraction.setMinimumSize(QtCore.QSize(0, 50))
        self.PB_Subtraction.setStyleSheet("background-color: rgb(255, 203, 246);\n"
"font: 75 22pt \"Arial Rounded MT Bold\";")
        self.PB_Subtraction.setObjectName("PB_Subtraction")
        self.PB_9 = QtGui.QPushButton(self.std_page)
        self.PB_9.setEnabled(True)
        self.PB_9.setGeometry(QtCore.QRect(179, 150, 89, 50))
        self.PB_9.setMinimumSize(QtCore.QSize(0, 50))
        self.PB_9.setStyleSheet("background-color: rgb(170, 255, 255);\n"
"font: 75 18pt \"Comic Sans MS\";")
        self.PB_9.setObjectName("PB_9")
        self.PB_2 = QtGui.QPushButton(self.std_page)
        self.PB_2.setEnabled(True)
        self.PB_2.setGeometry(QtCore.QRect(91, 272, 88, 50))
        self.PB_2.setMinimumSize(QtCore.QSize(0, 50))
        self.PB_2.setStyleSheet("background-color: rgb(170, 255, 255);\n"
"font: 75 18pt \"Comic Sans MS\";")
        self.PB_2.setObjectName("PB_2")
        self.PB_ClearAll = QtGui.QPushButton(self.std_page)
        self.PB_ClearAll.setEnabled(True)
        self.PB_ClearAll.setGeometry(QtCore.QRect(2, 89, 89, 50))
        self.PB_ClearAll.setMinimumSize(QtCore.QSize(0, 50))
        self.PB_ClearAll.setStyleSheet("font: 87 12pt \"Arial Black\";\n"
"background-color: rgb(179, 179, 179);\n"
"color: rgb(255, 0, 4);")
        self.PB_ClearAll.setObjectName("PB_ClearAll")
        self.PB_8 = QtGui.QPushButton(self.std_page)
        self.PB_8.setEnabled(True)
        self.PB_8.setGeometry(QtCore.QRect(91, 150, 88, 50))
        self.PB_8.setMinimumSize(QtCore.QSize(0, 50))
        self.PB_8.setStyleSheet("background-color: rgb(170, 255, 255);\n"
"font: 75 18pt \"Comic Sans MS\";")
        self.PB_8.setObjectName("PB_8")
        self.PB_7 = QtGui.QPushButton(self.std_page)
        self.PB_7.setEnabled(True)
        self.PB_7.setGeometry(QtCore.QRect(2, 150, 89, 50))
        self.PB_7.setMinimumSize(QtCore.QSize(0, 50))
        self.PB_7.setStyleSheet("background-color: rgb(170, 255, 255);\n"
"font: 75 18pt \"Comic Sans MS\";")
        self.PB_7.setObjectName("PB_7")
        self.PB_0 = QtGui.QPushButton(self.std_page)
        self.PB_0.setEnabled(True)
        self.PB_0.setGeometry(QtCore.QRect(91, 333, 88, 50))
        self.PB_0.setMinimumSize(QtCore.QSize(0, 50))
        self.PB_0.setStyleSheet("background-color: rgb(170, 255, 255);\n"
"font: 75 18pt \"Comic Sans MS\";")
        self.PB_0.setObjectName("PB_0")
        self.PB_ans = QtGui.QPushButton(self.std_page)
        self.PB_ans.setEnabled(True)
        self.PB_ans.setGeometry(QtCore.QRect(2, 333, 89, 50))
        self.PB_ans.setMinimumSize(QtCore.QSize(0, 50))
        self.PB_ans.setStyleSheet("background-color: rgb(94, 218, 255);\n"
"font: 87 20pt \"Arial Black\";")
        self.PB_ans.setObjectName("PB_ans")
        self.PB_4 = QtGui.QPushButton(self.std_page)
        self.PB_4.setEnabled(True)
        self.PB_4.setGeometry(QtCore.QRect(2, 211, 89, 50))
        self.PB_4.setMinimumSize(QtCore.QSize(0, 50))
        self.PB_4.setStyleSheet("background-color: rgb(170, 255, 255);\n"
"font: 75 18pt \"Comic Sans MS\";")
        self.PB_4.setObjectName("PB_4")
        self.PB_Backspace = QtGui.QPushButton(self.std_page)
        self.PB_Backspace.setEnabled(True)
        self.PB_Backspace.setGeometry(QtCore.QRect(91, 89, 177, 50))
        self.PB_Backspace.setMinimumSize(QtCore.QSize(0, 50))
        self.PB_Backspace.setStyleSheet("font: 75 14pt \"Comic Sans MS\";\n"
"background-color: rgb(179, 179, 179);")
        self.PB_Backspace.setObjectName("PB_Backspace")
        self.PB_5 = QtGui.QPushButton(self.std_page)
        self.PB_5.setEnabled(True)
        self.PB_5.setGeometry(QtCore.QRect(91, 211, 88, 50))
        self.PB_5.setMinimumSize(QtCore.QSize(0, 50))
        self.PB_5.setStyleSheet("background-color: rgb(170, 255, 255);\n"
"font: 75 18pt \"Comic Sans MS\";")
        self.PB_5.setObjectName("PB_5")
        self.PB_Addition = QtGui.QPushButton(self.std_page)
        self.PB_Addition.setEnabled(True)
        self.PB_Addition.setGeometry(QtCore.QRect(268, 271, 81, 51))
        self.PB_Addition.setMinimumSize(QtCore.QSize(0, 50))
        self.PB_Addition.setStyleSheet("background-color: rgb(255, 203, 246);\n"
"font: 75 22pt \"Arial Rounded MT Bold\";")
        self.PB_Addition.setObjectName("PB_Addition")
        self.PB_EqualsTo = QtGui.QPushButton(self.std_page)
        self.PB_EqualsTo.setEnabled(True)
        self.PB_EqualsTo.setGeometry(QtCore.QRect(268, 333, 81, 50))
        self.PB_EqualsTo.setMinimumSize(QtCore.QSize(0, 50))
        self.PB_EqualsTo.setStyleSheet("background-color: rgb(255, 170, 127);\n"
"font: 24pt \"MS Sans Serif\";")
        self.PB_EqualsTo.setObjectName("PB_EqualsTo")
        self.PB_6 = QtGui.QPushButton(self.std_page)
        self.PB_6.setEnabled(True)
        self.PB_6.setGeometry(QtCore.QRect(179, 211, 89, 50))
        self.PB_6.setMinimumSize(QtCore.QSize(0, 50))
        self.PB_6.setStyleSheet("background-color: rgb(170, 255, 255);\n"
"font: 75 18pt \"Comic Sans MS\";")
        self.PB_6.setObjectName("PB_6")
        self.PB_DecimalPoint = QtGui.QPushButton(self.std_page)
        self.PB_DecimalPoint.setEnabled(True)
        self.PB_DecimalPoint.setGeometry(QtCore.QRect(179, 333, 89, 50))
        self.PB_DecimalPoint.setMinimumSize(QtCore.QSize(0, 50))
        self.PB_DecimalPoint.setStyleSheet("background-color: rgb(170, 255, 255);\n"
"font: 75 28pt \"Comic Sans MS\";")
        self.PB_DecimalPoint.setObjectName("PB_DecimalPoint")
        self.PB_3 = QtGui.QPushButton(self.std_page)
        self.PB_3.setEnabled(True)
        self.PB_3.setGeometry(QtCore.QRect(179, 272, 89, 50))
        self.PB_3.setMinimumSize(QtCore.QSize(0, 50))
        self.PB_3.setStyleSheet("background-color: rgb(170, 255, 255);\n"
"font: 75 18pt \"Comic Sans MS\";")
        self.PB_3.setObjectName("PB_3")
        self.PB_1 = QtGui.QPushButton(self.std_page)
        self.PB_1.setEnabled(True)
        self.PB_1.setGeometry(QtCore.QRect(2, 272, 89, 50))
        self.PB_1.setMinimumSize(QtCore.QSize(0, 50))
        self.PB_1.setStyleSheet("background-color: rgb(170, 255, 255);\n"
"font: 75 18pt \"Comic Sans MS\";")
        self.PB_1.setObjectName("PB_1")
        self.PB_Division = QtGui.QPushButton(self.std_page)
        self.PB_Division.setEnabled(True)
        self.PB_Division.setGeometry(QtCore.QRect(268, 89, 81, 50))
        self.PB_Division.setMinimumSize(QtCore.QSize(0, 50))
        self.PB_Division.setStyleSheet("background-color: rgb(255, 203, 246);\n"
"font: 75 22pt \"Arial Rounded MT Bold\";")
        self.PB_Division.setObjectName("PB_Division")
        self.PB_Multiplication = QtGui.QPushButton(self.std_page)
        self.PB_Multiplication.setEnabled(True)
        self.PB_Multiplication.setGeometry(QtCore.QRect(268, 150, 81, 50))
        self.PB_Multiplication.setMinimumSize(QtCore.QSize(0, 50))
        self.PB_Multiplication.setStyleSheet("background-color: rgb(255, 203, 246);\n"
"font: 75 22pt \"Arial Rounded MT Bold\";")
        self.PB_Multiplication.setObjectName("PB_Multiplication")
        self.PB_cursorForward = QtGui.QPushButton(self.std_page)
        self.PB_cursorForward.setEnabled(True)
        self.PB_cursorForward.setGeometry(QtCore.QRect(176, 30, 89, 50))
        self.PB_cursorForward.setMinimumSize(QtCore.QSize(0, 50))
        self.PB_cursorForward.setStyleSheet("background-color: rgb(170, 255, 255);\n"
"font: 75 18pt \"Comic Sans MS\";")
        self.PB_cursorForward.setObjectName("PB_cursorForward")
        self.PB_cursorBackward = QtGui.QPushButton(self.std_page)
        self.PB_cursorBackward.setEnabled(True)
        self.PB_cursorBackward.setGeometry(QtCore.QRect(88, 30, 88, 50))
        self.PB_cursorBackward.setMinimumSize(QtCore.QSize(0, 50))
        self.PB_cursorBackward.setStyleSheet("background-color: rgb(170, 255, 255);\n"
"font: 75 18pt \"Comic Sans MS\";")
        self.PB_cursorBackward.setObjectName("PB_cursorBackward")
        self.layoutWidget = QtGui.QWidget(self.std_page)
        self.layoutWidget.setGeometry(QtCore.QRect(0, 390, 351, 51))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout = QtGui.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btn_open_paranthesis_2 = QtGui.QPushButton(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_open_paranthesis_2.sizePolicy().hasHeightForWidth())
        self.btn_open_paranthesis_2.setSizePolicy(sizePolicy)
        self.btn_open_paranthesis_2.setStyleSheet("font: 75 22pt \"MS PGothic\";\n"
"background-color: rgb(92, 170, 110);")
        self.btn_open_paranthesis_2.setObjectName("btn_open_paranthesis_2")
        self.horizontalLayout.addWidget(self.btn_open_paranthesis_2)
        self.btn_close_paranthesis_3 = QtGui.QPushButton(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_close_paranthesis_3.sizePolicy().hasHeightForWidth())
        self.btn_close_paranthesis_3.setSizePolicy(sizePolicy)
        self.btn_close_paranthesis_3.setStyleSheet("font: 75 22pt \"MS PGothic\";\n"
"background-color: rgb(92, 170, 110);")
        self.btn_close_paranthesis_3.setObjectName("btn_close_paranthesis_3")
        self.horizontalLayout.addWidget(self.btn_close_paranthesis_3)
        self.btn_close_paranthesis_2 = QtGui.QPushButton(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_close_paranthesis_2.sizePolicy().hasHeightForWidth())
        self.btn_close_paranthesis_2.setSizePolicy(sizePolicy)
        self.btn_close_paranthesis_2.setStyleSheet("font: 75 22pt \"MS PGothic\";\n"
"background-color: rgb(92, 170, 110);")
        self.btn_close_paranthesis_2.setObjectName("btn_close_paranthesis_2")
        self.horizontalLayout.addWidget(self.btn_close_paranthesis_2)
        self.stackedWidget.addWidget(self.std_page)
        self.adv_page = QtGui.QWidget()
        self.adv_page.setObjectName("adv_page")
        self.frame_3 = QtGui.QFrame(self.adv_page)
        self.frame_3.setGeometry(QtCore.QRect(0, 30, 391, 421))
        self.frame_3.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.layoutWidget1 = QtGui.QWidget(self.frame_3)
        self.layoutWidget1.setGeometry(QtCore.QRect(5, 0, 341, 421))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.gridLayout_2 = QtGui.QGridLayout(self.layoutWidget1)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.btn_cos = QtGui.QPushButton(self.layoutWidget1)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_cos.sizePolicy().hasHeightForWidth())
        self.btn_cos.setSizePolicy(sizePolicy)
        self.btn_cos.setStyleSheet("font: 75 12pt \"Comic Sans MS\";\n"
"background-color: rgb(156, 199, 255);")
        self.btn_cos.setObjectName("btn_cos")
        self.gridLayout_2.addWidget(self.btn_cos, 0, 1, 1, 1)
        self.btn_sin = QtGui.QPushButton(self.layoutWidget1)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_sin.sizePolicy().hasHeightForWidth())
        self.btn_sin.setSizePolicy(sizePolicy)
        self.btn_sin.setStyleSheet("font: 75 12pt \"Comic Sans MS\";\n"
"background-color: rgb(156, 199, 255);")
        self.btn_sin.setObjectName("btn_sin")
        self.gridLayout_2.addWidget(self.btn_sin, 0, 0, 1, 1)
        self.btn_arcsinh = QtGui.QPushButton(self.layoutWidget1)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_arcsinh.sizePolicy().hasHeightForWidth())
        self.btn_arcsinh.setSizePolicy(sizePolicy)
        self.btn_arcsinh.setStyleSheet("font: 75 12pt \"Comic Sans MS\";\n"
"background-color: rgb(156, 199, 255);")
        self.btn_arcsinh.setObjectName("btn_arcsinh")
        self.gridLayout_2.addWidget(self.btn_arcsinh, 3, 0, 1, 1)
        self.btn_arctanh = QtGui.QPushButton(self.layoutWidget1)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_arctanh.sizePolicy().hasHeightForWidth())
        self.btn_arctanh.setSizePolicy(sizePolicy)
        self.btn_arctanh.setStyleSheet("font: 75 12pt \"Comic Sans MS\";\n"
"background-color: rgb(156, 199, 255);")
        self.btn_arctanh.setObjectName("btn_arctanh")
        self.gridLayout_2.addWidget(self.btn_arctanh, 3, 2, 1, 1)
        self.btn_c = QtGui.QPushButton(self.layoutWidget1)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_c.sizePolicy().hasHeightForWidth())
        self.btn_c.setSizePolicy(sizePolicy)
        self.btn_c.setStyleSheet("font: 75 10pt \"Comic Sans MS\";\n"
"background-color: rgb(215, 92, 255);")
        self.btn_c.setObjectName("btn_c")
        self.gridLayout_2.addWidget(self.btn_c, 3, 3, 1, 1)
        self.btn_e = QtGui.QPushButton(self.layoutWidget1)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_e.sizePolicy().hasHeightForWidth())
        self.btn_e.setSizePolicy(sizePolicy)
        self.btn_e.setStyleSheet("font: 75 10pt \"Comic Sans MS\";\n"
"background-color: rgb(215, 92, 255);")
        self.btn_e.setObjectName("btn_e")
        self.gridLayout_2.addWidget(self.btn_e, 1, 3, 1, 1)
        self.btn_arcsin = QtGui.QPushButton(self.layoutWidget1)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_arcsin.sizePolicy().hasHeightForWidth())
        self.btn_arcsin.setSizePolicy(sizePolicy)
        self.btn_arcsin.setStyleSheet("font: 75 12pt \"Comic Sans MS\";\n"
"background-color: rgb(156, 199, 255);")
        self.btn_arcsin.setObjectName("btn_arcsin")
        self.gridLayout_2.addWidget(self.btn_arcsin, 1, 0, 1, 1)
        self.btn_tan = QtGui.QPushButton(self.layoutWidget1)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_tan.sizePolicy().hasHeightForWidth())
        self.btn_tan.setSizePolicy(sizePolicy)
        self.btn_tan.setStyleSheet("font: 75 12pt \"Comic Sans MS\";\n"
"background-color: rgb(156, 199, 255);")
        self.btn_tan.setObjectName("btn_tan")
        self.gridLayout_2.addWidget(self.btn_tan, 0, 2, 1, 1)
        self.btn_arctan = QtGui.QPushButton(self.layoutWidget1)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_arctan.sizePolicy().hasHeightForWidth())
        self.btn_arctan.setSizePolicy(sizePolicy)
        self.btn_arctan.setStyleSheet("font: 75 12pt \"Comic Sans MS\";\n"
"background-color: rgb(156, 199, 255);")
        self.btn_arctan.setObjectName("btn_arctan")
        self.gridLayout_2.addWidget(self.btn_arctan, 1, 2, 1, 1)
        self.btn_ceil = QtGui.QPushButton(self.layoutWidget1)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_ceil.sizePolicy().hasHeightForWidth())
        self.btn_ceil.setSizePolicy(sizePolicy)
        self.btn_ceil.setStyleSheet("font: 75 12pt \"Comic Sans MS\";\n"
"background-color: rgb(156, 199, 255);")
        self.btn_ceil.setObjectName("btn_ceil")
        self.gridLayout_2.addWidget(self.btn_ceil, 4, 1, 1, 1)
        self.btn_sinh = QtGui.QPushButton(self.layoutWidget1)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_sinh.sizePolicy().hasHeightForWidth())
        self.btn_sinh.setSizePolicy(sizePolicy)
        self.btn_sinh.setStyleSheet("font: 75 12pt \"Comic Sans MS\";\n"
"background-color: rgb(156, 199, 255);")
        self.btn_sinh.setObjectName("btn_sinh")
        self.gridLayout_2.addWidget(self.btn_sinh, 2, 0, 1, 1)
        self.btn_cosh = QtGui.QPushButton(self.layoutWidget1)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_cosh.sizePolicy().hasHeightForWidth())
        self.btn_cosh.setSizePolicy(sizePolicy)
        self.btn_cosh.setStyleSheet("font: 75 12pt \"Comic Sans MS\";\n"
"background-color: rgb(156, 199, 255);")
        self.btn_cosh.setObjectName("btn_cosh")
        self.gridLayout_2.addWidget(self.btn_cosh, 2, 1, 1, 1)
        self.btn_floor = QtGui.QPushButton(self.layoutWidget1)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_floor.sizePolicy().hasHeightForWidth())
        self.btn_floor.setSizePolicy(sizePolicy)
        self.btn_floor.setStyleSheet("font: 75 12pt \"Comic Sans MS\";\n"
"background-color: rgb(156, 199, 255);")
        self.btn_floor.setObjectName("btn_floor")
        self.gridLayout_2.addWidget(self.btn_floor, 4, 0, 1, 1)
        self.btn_arccos = QtGui.QPushButton(self.layoutWidget1)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_arccos.sizePolicy().hasHeightForWidth())
        self.btn_arccos.setSizePolicy(sizePolicy)
        self.btn_arccos.setStyleSheet("font: 75 12pt \"Comic Sans MS\";\n"
"background-color: rgb(156, 199, 255);")
        self.btn_arccos.setObjectName("btn_arccos")
        self.gridLayout_2.addWidget(self.btn_arccos, 1, 1, 1, 1)
        self.btn_h = QtGui.QPushButton(self.layoutWidget1)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_h.sizePolicy().hasHeightForWidth())
        self.btn_h.setSizePolicy(sizePolicy)
        self.btn_h.setStyleSheet("font: 75 10pt \"Comic Sans MS\";\n"
"background-color: rgb(215, 92, 255);")
        self.btn_h.setObjectName("btn_h")
        self.gridLayout_2.addWidget(self.btn_h, 2, 3, 1, 1)
        self.btn_tanh = QtGui.QPushButton(self.layoutWidget1)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_tanh.sizePolicy().hasHeightForWidth())
        self.btn_tanh.setSizePolicy(sizePolicy)
        self.btn_tanh.setStyleSheet("font: 75 12pt \"Comic Sans MS\";\n"
"background-color: rgb(156, 199, 255);")
        self.btn_tanh.setObjectName("btn_tanh")
        self.gridLayout_2.addWidget(self.btn_tanh, 2, 2, 1, 1)
        self.btn_arccosh = QtGui.QPushButton(self.layoutWidget1)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_arccosh.sizePolicy().hasHeightForWidth())
        self.btn_arccosh.setSizePolicy(sizePolicy)
        self.btn_arccosh.setStyleSheet("font: 75 12pt \"Comic Sans MS\";\n"
"background-color: rgb(156, 199, 255);")
        self.btn_arccosh.setObjectName("btn_arccosh")
        self.gridLayout_2.addWidget(self.btn_arccosh, 3, 1, 1, 1)
        self.btn_remainder = QtGui.QPushButton(self.layoutWidget1)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_remainder.sizePolicy().hasHeightForWidth())
        self.btn_remainder.setSizePolicy(sizePolicy)
        self.btn_remainder.setStyleSheet("font: 75 12pt \"Comic Sans MS\";\n"
"background-color: rgb(156, 199, 255);")
        self.btn_remainder.setObjectName("btn_remainder")
        self.gridLayout_2.addWidget(self.btn_remainder, 4, 2, 1, 1)
        self.btn_exp = QtGui.QPushButton(self.layoutWidget1)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_exp.sizePolicy().hasHeightForWidth())
        self.btn_exp.setSizePolicy(sizePolicy)
        self.btn_exp.setStyleSheet("\n"
"background-color: rgb(156, 199, 255);\n"
"font: 75 9pt \"Comic Sans MS\";")
        self.btn_exp.setObjectName("btn_exp")
        self.gridLayout_2.addWidget(self.btn_exp, 5, 0, 1, 1)
        self.btn_close_paranthesis = QtGui.QPushButton(self.layoutWidget1)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_close_paranthesis.sizePolicy().hasHeightForWidth())
        self.btn_close_paranthesis.setSizePolicy(sizePolicy)
        self.btn_close_paranthesis.setStyleSheet("font: 75 22pt \"MS PGothic\";\n"
"background-color: rgb(92, 170, 110);")
        self.btn_close_paranthesis.setObjectName("btn_close_paranthesis")
        self.gridLayout_2.addWidget(self.btn_close_paranthesis, 6, 3, 1, 1)
        self.btn_abs = QtGui.QPushButton(self.layoutWidget1)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_abs.sizePolicy().hasHeightForWidth())
        self.btn_abs.setSizePolicy(sizePolicy)
        self.btn_abs.setStyleSheet("font: 75 12pt \"Comic Sans MS\";\n"
"background-color: rgb(156, 199, 255);")
        self.btn_abs.setObjectName("btn_abs")
        self.gridLayout_2.addWidget(self.btn_abs, 6, 2, 1, 1)
        self.btn_pow = QtGui.QPushButton(self.layoutWidget1)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_pow.sizePolicy().hasHeightForWidth())
        self.btn_pow.setSizePolicy(sizePolicy)
        self.btn_pow.setStyleSheet("font: 75 12pt \"Comic Sans MS\";\n"
"background-color: rgb(156, 199, 255);")
        self.btn_pow.setObjectName("btn_pow")
        self.gridLayout_2.addWidget(self.btn_pow, 6, 0, 1, 1)
        self.btn_open_paranthesis = QtGui.QPushButton(self.layoutWidget1)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_open_paranthesis.sizePolicy().hasHeightForWidth())
        self.btn_open_paranthesis.setSizePolicy(sizePolicy)
        self.btn_open_paranthesis.setStyleSheet("font: 75 22pt \"MS PGothic\";\n"
"background-color: rgb(92, 170, 110);")
        self.btn_open_paranthesis.setObjectName("btn_open_paranthesis")
        self.gridLayout_2.addWidget(self.btn_open_paranthesis, 5, 3, 1, 1)
        self.btn_sqroot = QtGui.QPushButton(self.layoutWidget1)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_sqroot.sizePolicy().hasHeightForWidth())
        self.btn_sqroot.setSizePolicy(sizePolicy)
        self.btn_sqroot.setStyleSheet("font: 75 12pt \"Comic Sans MS\";\n"
"background-color: rgb(156, 199, 255);")
        self.btn_sqroot.setObjectName("btn_sqroot")
        self.gridLayout_2.addWidget(self.btn_sqroot, 6, 1, 1, 1)
        self.btn_ln = QtGui.QPushButton(self.layoutWidget1)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_ln.sizePolicy().hasHeightForWidth())
        self.btn_ln.setSizePolicy(sizePolicy)
        self.btn_ln.setStyleSheet("font: 75 12pt \"Comic Sans MS\";\n"
"background-color: rgb(156, 199, 255);")
        self.btn_ln.setObjectName("btn_ln")
        self.gridLayout_2.addWidget(self.btn_ln, 5, 1, 1, 1)
        self.btn_log10 = QtGui.QPushButton(self.layoutWidget1)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_log10.sizePolicy().hasHeightForWidth())
        self.btn_log10.setSizePolicy(sizePolicy)
        self.btn_log10.setStyleSheet("font: 75 12pt \"Comic Sans MS\";\n"
"background-color: rgb(156, 199, 255);")
        self.btn_log10.setObjectName("btn_log10")
        self.gridLayout_2.addWidget(self.btn_log10, 5, 2, 1, 1)
        self.btn_pi = QtGui.QPushButton(self.layoutWidget1)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_pi.sizePolicy().hasHeightForWidth())
        self.btn_pi.setSizePolicy(sizePolicy)
        self.btn_pi.setStyleSheet("font: 75 10pt \"Comic Sans MS\";\n"
"background-color: rgb(215, 92, 255);")
        self.btn_pi.setObjectName("btn_pi")
        self.gridLayout_2.addWidget(self.btn_pi, 0, 3, 1, 1)
        self.PB_EqualsTo_2 = QtGui.QPushButton(self.layoutWidget1)
        self.PB_EqualsTo_2.setEnabled(True)
        self.PB_EqualsTo_2.setMinimumSize(QtCore.QSize(0, 50))
        self.PB_EqualsTo_2.setStyleSheet("background-color: rgb(255, 170, 127);\n"
"font: 24pt \"MS Sans Serif\";")
        self.PB_EqualsTo_2.setObjectName("PB_EqualsTo_2")
        self.gridLayout_2.addWidget(self.PB_EqualsTo_2, 4, 3, 1, 1)
        self.stackedWidget.addWidget(self.adv_page)
        self.LineDisplay = QtGui.QLineEdit(self.frame_2)
        self.LineDisplay.setGeometry(QtCore.QRect(10, 0, 351, 51))
        self.LineDisplay.setStyleSheet("font: 75 20pt \"Arial Narrow\";")
        self.LineDisplay.setText("")
        self.LineDisplay.setObjectName("LineDisplay")
        self.LCDDisplay = QtGui.QLCDNumber(self.frame_2)
        self.LCDDisplay.setGeometry(QtCore.QRect(10, 70, 351, 51))
        self.LCDDisplay.setObjectName("LCDDisplay")
        self.StdBtn = QtGui.QPushButton(self.frame_2)
        self.StdBtn.setGeometry(QtCore.QRect(9, 130, 171, 51))
        self.StdBtn.setStyleSheet("background-color: rgb(0, 255, 127);\n"
"font: 75 11pt \"Cambria Math\";")
        self.StdBtn.setObjectName("StdBtn")
        self.AdvBtn = QtGui.QPushButton(self.frame_2)
        self.AdvBtn.setGeometry(QtCore.QRect(190, 130, 171, 51))
        self.AdvBtn.setStyleSheet("background-color: rgb(0, 255, 127);\n"
"font: 75 11pt \"Cambria Math\";")
        self.AdvBtn.setObjectName("AdvBtn")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "Calculator", None, QtGui.QApplication.UnicodeUTF8))
        self.PB_Subtraction.setText(QtGui.QApplication.translate("MainWindow", "-", None, QtGui.QApplication.UnicodeUTF8))
        self.PB_9.setText(QtGui.QApplication.translate("MainWindow", "9", None, QtGui.QApplication.UnicodeUTF8))
        self.PB_2.setText(QtGui.QApplication.translate("MainWindow", "2", None, QtGui.QApplication.UnicodeUTF8))
        self.PB_ClearAll.setText(QtGui.QApplication.translate("MainWindow", "Clear All", None, QtGui.QApplication.UnicodeUTF8))
        self.PB_8.setText(QtGui.QApplication.translate("MainWindow", "8", None, QtGui.QApplication.UnicodeUTF8))
        self.PB_7.setText(QtGui.QApplication.translate("MainWindow", "7", None, QtGui.QApplication.UnicodeUTF8))
        self.PB_0.setText(QtGui.QApplication.translate("MainWindow", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.PB_ans.setText(QtGui.QApplication.translate("MainWindow", "Ans", None, QtGui.QApplication.UnicodeUTF8))
        self.PB_4.setText(QtGui.QApplication.translate("MainWindow", "4", None, QtGui.QApplication.UnicodeUTF8))
        self.PB_Backspace.setText(QtGui.QApplication.translate("MainWindow", "Backspace", None, QtGui.QApplication.UnicodeUTF8))
        self.PB_5.setText(QtGui.QApplication.translate("MainWindow", "5", None, QtGui.QApplication.UnicodeUTF8))
        self.PB_Addition.setText(QtGui.QApplication.translate("MainWindow", "+", None, QtGui.QApplication.UnicodeUTF8))
        self.PB_EqualsTo.setText(QtGui.QApplication.translate("MainWindow", "=", None, QtGui.QApplication.UnicodeUTF8))
        self.PB_6.setText(QtGui.QApplication.translate("MainWindow", "6", None, QtGui.QApplication.UnicodeUTF8))
        self.PB_DecimalPoint.setText(QtGui.QApplication.translate("MainWindow", ".", None, QtGui.QApplication.UnicodeUTF8))
        self.PB_3.setText(QtGui.QApplication.translate("MainWindow", "3", None, QtGui.QApplication.UnicodeUTF8))
        self.PB_1.setText(QtGui.QApplication.translate("MainWindow", "1", None, QtGui.QApplication.UnicodeUTF8))
        self.PB_Division.setText(QtGui.QApplication.translate("MainWindow", "÷", None, QtGui.QApplication.UnicodeUTF8))
        self.PB_Multiplication.setText(QtGui.QApplication.translate("MainWindow", "X", None, QtGui.QApplication.UnicodeUTF8))
        self.PB_cursorForward.setText(QtGui.QApplication.translate("MainWindow", ">", None, QtGui.QApplication.UnicodeUTF8))
        self.PB_cursorBackward.setText(QtGui.QApplication.translate("MainWindow", "<", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_open_paranthesis_2.setText(QtGui.QApplication.translate("MainWindow", "(", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_close_paranthesis_3.setText(QtGui.QApplication.translate("MainWindow", ",", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_close_paranthesis_2.setText(QtGui.QApplication.translate("MainWindow", ")", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_cos.setText(QtGui.QApplication.translate("MainWindow", "cos(", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_sin.setText(QtGui.QApplication.translate("MainWindow", "sin(", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_arcsinh.setText(QtGui.QApplication.translate("MainWindow", "arc-sinh(", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_arctanh.setText(QtGui.QApplication.translate("MainWindow", "arc-tanh(", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_c.setText(QtGui.QApplication.translate("MainWindow", "Const \'c\'", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_e.setText(QtGui.QApplication.translate("MainWindow", "Const \'e\'", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_arcsin.setText(QtGui.QApplication.translate("MainWindow", "arc-sin(", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_tan.setText(QtGui.QApplication.translate("MainWindow", "tan(", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_arctan.setText(QtGui.QApplication.translate("MainWindow", "arc-tan(", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_ceil.setText(QtGui.QApplication.translate("MainWindow", "ceil(", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_sinh.setText(QtGui.QApplication.translate("MainWindow", "sinh(", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_cosh.setText(QtGui.QApplication.translate("MainWindow", "cosh(", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_floor.setText(QtGui.QApplication.translate("MainWindow", "floor(", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_arccos.setText(QtGui.QApplication.translate("MainWindow", "arc-cos(", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_h.setText(QtGui.QApplication.translate("MainWindow", "Const \'h\'", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_tanh.setText(QtGui.QApplication.translate("MainWindow", "tanh(", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_arccosh.setText(QtGui.QApplication.translate("MainWindow", "arc-cosh(", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_remainder.setText(QtGui.QApplication.translate("MainWindow", "remainder(", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_exp.setText(QtGui.QApplication.translate("MainWindow", "EXP(e pow x)", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_close_paranthesis.setText(QtGui.QApplication.translate("MainWindow", ")", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_abs.setText(QtGui.QApplication.translate("MainWindow", "Absolute(", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_pow.setText(QtGui.QApplication.translate("MainWindow", "pow(x,y", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_open_paranthesis.setText(QtGui.QApplication.translate("MainWindow", "(", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_sqroot.setText(QtGui.QApplication.translate("MainWindow", "SqRoot(", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_ln.setText(QtGui.QApplication.translate("MainWindow", "ln(", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_log10.setText(QtGui.QApplication.translate("MainWindow", "log10(", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_pi.setText(QtGui.QApplication.translate("MainWindow", "Const \'Pi\'", None, QtGui.QApplication.UnicodeUTF8))
        self.PB_EqualsTo_2.setText(QtGui.QApplication.translate("MainWindow", "=", None, QtGui.QApplication.UnicodeUTF8))
        self.StdBtn.setText(QtGui.QApplication.translate("MainWindow", "Standard Buttons", None, QtGui.QApplication.UnicodeUTF8))
        self.AdvBtn.setText(QtGui.QApplication.translate("MainWindow", "Advance Buttons", None, QtGui.QApplication.UnicodeUTF8))

